Issue 16 🐛 fix timeouts for Freenom World DNS in DE by using second server instead of first server
PeterDaveHello/chkdomain pull request #17
Opened 2023-05-08 14:27 UTC by thomasmerz

This PR solves issue #16

2023-05-10 21:06 UTC, PeterDaveHello requested changes
Why's the order shuffled?

2023-05-10 21:06 UTC, PeterDaveHello commented on README.md
> +| [Freenom World][Freenom World] (`80.80.81.81`) | [CONTROL D][CONTROL D] (`76.76.2.1`)             | [dnsforge.de][dnsforge.de] (`49.12.223.2`) |
dnsforge.de is not related here

2023-05-10 21:06 UTC, PeterDaveHello commented on chkdm
> +adblockDNS[clean.dnsforge.de]="49.12.223.2"
same here

2023-05-11 07:26 UTC, thomasmerz commented
⚠️  Do not merge, because problem to be fixed was a temporary one. ⚠️ 

Regarding your questions:
- I sorted the list alphabetically
- dnsforge.de came from https://github.com/PeterDaveHello/chkdomain/pull/14 which was closed

I'm fine with your questions 👍🏼

2023-05-11 07:26 UTC, closed without merging